# For most purposes, use the top-level stack.yaml file.

# This is just here to quickly bring up an emacs REPL without bringing
# in other nonsense.

flags: {}
packages:
- '.'
extra-deps: []
resolver: lts-3.8
