# For most purposes, use the top-level stack.yaml file.

# This is just here to quickly bring up an emacs REPL without bringing
# in other nonsense.

flags: {}
packages:
- '.'
extra-deps:
- tasty-program-1.0.3
resolver: lts-3.8
