

all: step1 step2

# These steps are really per-package and could be broken up that way
# ------------------------------------------------------------------
step1:
	./GrabNewestPerPackage.hs

step2:
	./UntarFiles.hs

step3:
# Gather DDefs from each discovered haskell file.
# Organize output in per-package directories.


# ------------------------------------------------------------------
